### ISSUE TITLE
error with using "Frame" in featuredPage

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#16]
Hi Jim,
I just tried to have a look at the "Frame"; one of the featured page display options but got an error. Both the "Bleed" and "None" option work fine.
Pls see screenshot below.
![Screen Shot 2022-01-06 at 1 23 46 pm](https://user-images.githubusercontent.com/6309595/148318623-f8e5554f-1f21-40c6-95b5-e9774d6426e9.png)

Maybe this issues is related to this [issue](https://github.com/jamestagal/edtechdesigner/issues/3) @roobyz

**Comment by roobyz** [comment]
@jamestagal, thanks for raising this. I have uncovered the issue. I'll work on pushing a fix out.

**Comment by roobyz** [comment]
Hi @jamestagal, please pull the latest theme. I made a big push with commits that fix the bug you highlighted, plus some other cleanup, refactor to make it more DRY, and refinements to the theme

**Comment by jamestagal** [comment]
Hi Roberto,

thanks for letting me know. I run  a ``` plenti theme update comdendium``` which updated my theme folder to the latest hash commit cbc6ceed503735ad364937cca5a66a24c49987bc
However I noticed now the white text for part of the site name and nav is now black so I can't see them until I hover. See screenshot.
![Screen Shot 2022-01-18 at 10 10 22 am](https://user-images.githubusercontent.com/6309595/149846457-0bee7917-937a-4d75-af69-01a92bbc96f5.png)

Did you change the text colour for the colourScheme for Technobeat? i am a little confused here because I had copied over the themes CSS into the Styles folder in my project so I thought i would be still using my version.

Also I noticed that the svelte files that I have modified in my project (outside of the theme folder) will not reflect the changes you just made...is there an easy way to merge those changes into my project? I haven't committed your recent change to my repo so the changes are just in my project locally.

**Comment by roobyz** [comment]
Hi Benjamin,

Super cool that updating the theme is so seamless. Looks like you are on the correct version. I did not change the css files. I did, however, make significant changes to components in `layouts/`. Your fix was 1 of 20 [commits](https://github.com/plenti-themes/compendium/commits/main) that I made today. There were a bunch of other little fixes, cleanups, and enhancements.

Because we are using git, my recommendation would be to copy over each of the components that you customized from the themes folder into your project `layouts/` folder. I'm assuming that you are using VSCode or similar to edit your code. If so, you can click on the *source control* icon to get the list of uncommitted changes. Then you will be able to click on each file to see the **diffs** between your version and my updated file. Then you will be able to incorporate your changes or revert the file altogether as desired.

That said, there are four commits that you should look at. One of which is the likely culprit:
* the ` layouts/content/index.svelte` [bug fix](https://github.com/plenti-themes/compendium/commit/8d6217e0a3eff81ead2bc45afd1e3aea73dba108) for "Frame"
* the `layouts/style/global.svelte` [bug fix](https://github.com/plenti-themes/compendium/commit/63f338bff61ed08934c073fb88626bd31085bfda) -- this one contains two class renames which impact:
    * `layouts/global/`[footer.svelte](https://github.com/plenti-themes/compendium/commit/e18c5d28e36b901cebf56fa1873c4d2b505880d6) -- rename class from ***footer*** to ***footnote***
    *  `layouts/global/`[navbar.svelte](https://github.com/plenti-themes/compendium/commit/d5c31cff2cc589cf3611a40580360b80a859d182) --  rename class from ***menu*** to ***navmenu*** --> your likely ***white font*** challenge
    * also contains fixes for ordered lists

The remaining commits contain changes for:
* ordering posts in descending order, etc. 
* post meta-data refactor with a svelte component so the code is DRY and easier to maintain

The class renames are part of a broader theme refactor that I am working on for a more robust, general, and easier to implement template.

**Comment by roobyz** [comment]
BTW... you could revert the class renames and just incorporate the bug fixes. This would give you no refactor now for a potentially bigger refactor tomorrow, if you want to stay in sync with the theme in the future. ;-)

**Comment by jamestagal** [comment]
Hi @roobyz Thanks for all this information. I am in the process of incorporating your changes to my modified versions.  All seems to be going well.  
I have a question regarding the this commit: **Sort projects posts by project**
[https://github.com/plenti-themes/compendium/commit/321dfad2fa83571811c9c18a11b46549bd3cc1e6](url)
```svelte
  // Sort project posts in ascending order
  allProjs.sort(function(a, b) {
    // var s = new Date(b.fields.dateModified).getTime() - new Date(a.fields.dateModified).getTime();
    var p = a.fields.project.localeCompare(b.fields.project)
    return p == 0? a.path.localeCompare(b.path) : p;
  });
```
I am guessing this code is sorting based on alphabetical order? Because I saw that change in my code.

Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal,

Yeah, I find that JS is a bit obtuse at times. The p variable is a comparison between the project names. If the posts belong to the same project (p==0) then it returns the comparison between the post names to sort them alphabetically within a project, else it sorts the projects alphabetically.

Have a look at my [project page](https://www.quantifiedleap.com/projs/) to see how this works in practice. Which by the way, goes into my thinking around how I plan to streamline the theming.

I believe that ideal state would be the projects get sorted chronologically, and the posts alphabetically within a project. I haven't figured out how to accomplish this, yet. Feedback, welcomed. ;-)

**Comment by jamestagal** [comment]
Hi @roobyz 
That's great..I like your site and the text styles and colours etc..Nice! 
I have modified my code to show Projects as Posts because I don't think I would have projects per se but individual posts.. 
[https://vigorous-einstein-b90548.netlify.app/posts/](url)
But I like that I can name similar posts/projects and group them around similar topics. And then Categories and Tags further help find content. For instance I have Posts on Speaking Events and Learning Vietnamese so I have grouped them accordingly. 
Thanks for all your work on this. It tremendous.
BTW. @jimafisk helped me implement sorting posts chronologically from posts (dateCreated) see issue below. 
https://github.com/jamestagal/edtechdesigner/issues/13
Hope that helps,
Regards,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal

Thanks for the feedback! Much appreciated. ;-)

I like how your repurposed "Projects". Very creative. It shows that my design is flexible, too. Yeah @jimafisk has provided stellar support and a great project!

Would you say that this issue is resolved now?

Cheers,
Roberto

**Comment by jimafisk** [comment]
Love the collab guys! @roobyz thanks for taking a look at these issues, I'm super impressed with all the fixes / improvements you've pushed over the last couple of days! @jamestagal nice job sticking with the subtheming. your site is coming out awesome!

**Comment by jamestagal** [comment]
Thanks again for all your work @roobyz  and @jimafisk . I appreciate the support and your project.

**Comment by roobyz** [comment]
> sort

BTW... thanks for this insight. I remember now that Jim had provided me that sort module and I had forgotten it. I'm going to implement it, as well. I think it will make for much more readable code. I'll create a new function for sort_by_post, so that folks can easily swap. ;-)

Cheers,
Roberto
