### ISSUE TITLE
Carousel Overlay Text misplaced after theme update

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#20]
hello @roobyz
The position of Carousel Overlay Text in the featured.svelte file is too low but I can't see where the css is to change it.

![Screen Shot 2022-01-26 at 1 24 06 pm](https://user-images.githubusercontent.com/6309595/151093492-1bc2f8f0-0439-41e2-acdf-266ebeab772d.png)

Could you please have a look and point me to the element i need to change to get it sitting hight in the frame?

Cheers,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal ,

One nice thing about svelte is that the style block in the component will override any global styles. This comes in handy for the feature section because the style for it is rather unique for the site. ;-)

That said, the style for the feature component is in the `featured.svelte` layout itself. Look at the bottom of the file and change the "bottom" spacing in the style block to something like 15% Since your title wraps for one of your posts, it will likely bump the hover for any lower value.

``` css
  .feature {
    bottom: 15%;
  }
```

Roberto

**Comment by jamestagal** [comment]
hi @roobyz 

Thanks for that.  Yes Svelte was one of the reasons I got interested in the Plenti project. I am trying to learn Javascript as a hobby and I thought Svelte looked to be a great beginner friendly way to get started.  I think your theme uses very advanced techniques which is good but is sometimes a struggle for me as a beginner. 

Regards,
Ben

**Comment by roobyz** [comment]
Funny thing @jamestagal... I created this template as a way to learn Javascript and picked Plenti for the same reason. ;-)

It was pretty rough at first. Jim helped me to understand some of the key functionality to use including Svelte components, keys and functions. I've been programming for almost 40 years and studied computer engineering, so I might have an advantage. As a matter of course, I will refactor my code and comment it using Agile methodology so that it becomes cleaner and clearer as I progress. So at this point, it is actually in pretty decent shape. Your feedback and questions has helped me to make it even better!

Regards,
Roberto

**Comment by jamestagal** [comment]
Well @roobyz  I feel fortunate to have started with the Plenti project as @jimafisk is creating an awesome tool/platform and your theme is too. You have been really responsive to changes and improvements and helping me customise my version of your theme. So thank you for that support.  I really like the way you have implemented it, it is so powerful: so many great features particularly the ability to find posts from categories, tags and this postsGroup is awesome functionality from both author and user perspective. It gives a tonne of options and customisability. I come from teaching/education technology background so programming and JavaScript is a challenge but nevertheless an interest and a good progression from the HTML and CSS knowledge I have learnt through my job which these days is building course material for online learning. 

Regards,
Ben
