### ISSUE TITLE
'Undefined' element on Posts page after theme update

### ISSUE THREAD

**Issue by jamestagal** [jamestagal/edtechdesigner#21]
Hello @roobyz

On my Posts page, I have an 'undefined' element and I think it comes from the cards_projs.svelte file and relates to the following property.
```svelte
{proj.name}
```
[https://vigorous-einstein-b90548.netlify.app/posts/](url)

Also where can I find place to edit the description here? I noticed the text "Cr" underneath the title.
 
Could you please have a look and let me know what i did wrong when i updated these change.

Best regards,
Ben

**Comment by roobyz** [comment]
Hi @jamestagal ,

You inadvertently introduced a bug to your project by changing the key on each post from "project" to "posts", because the layout uses that key for organizing the posts.

The most correct fix would be to rename that key back to "project" for each of your posts. Otherwise you'll need to change your `projs.svelte` on a number of lines to look for your new posts key. This would need to happen any time there is a layout change. Although that shouldn't happen too often.

My original intent was that "project" is really more of a "grouping" for posts. Should I update the template to rename the key to "group" or "grouping"? For example:

``` json
{
  "title": "Employment Timeline",
  "group": "Curriculum Vitae",
  ...
}
```

Also, on line 6 of  `cards_proj.svelte` you should change the variable to false like:

``` js
  let projTLDR = false;
```

Cheers,
Roberto

**Comment by jamestagal** [comment]
hi @roobyz 
I see. Thank you. I have modified that variable. What does it do?

I think postsGroup would be a little more descriptive.  But happy with whatever you use. 

Cheers,
Ben

**Comment by roobyz** [comment]
hi @jamestagal ,

I'll update the key to postsGroup. 

In the "Posts" link in your Navbar, it drives the card groupings. For example, for "Speaking Events" you would have a card with a heading called "Speaking Events" containing the posts that belong in that card.

In my case, postsGroup will be for project categories... in your case, it will be a group by type of posts.

Roberto

**Comment by jamestagal** [comment]
Hi @roobyz 
Yes thanks. 

How about this projTLDR ? what is it turning on or off with true and false?
``` js
  let projTLDR = false;
```
Cheers,
Ben

**Comment by roobyz** [comment]
In the postsGroup card that I mentioned above... when setup as a project it lists the description of the first post in the project, which in my case gives the introduction of the overall project. Maybe I should rename to "projDescription". :-)

It wouldn't apply in your use-case, since each post may be unrelated to each other, even though they belong to the same grouping.

Cheers,
Roberto
